#!/usr/bin/env bash

while inotifywait -e close_write presentation.tex; do
  nix-shell shell.nix --run 'pdflatex -shell-escape presentation.tex; pdflatex -shell-escape presentation.tex; pdflatex -shell-escape presentation.tex'
done
